### ISSUE TITLE
Já tem PIX?

### ISSUE THREAD

**Issue by quinhone** [jhernandes/ipag-sdk-php#13]
Já tem PIX integrado, tem exemplo de como usá-lo?

**Comment by jhernandes** [comment]
Bom dia @quinhone através do SDK ainda não é possível criar uma transação via Pix. No momento, é necessário seguir a documentação do iPag: https://developers.ipag.com.br/pt-br/payment?id=criar-pagamento (Exemplo de Pagamento via Pix).

Outro ponto importante, é ter o método Pix configurado e homologado em sua conta. (Disponível somente em Produção)

**Comment by jhernandes** [comment]
Olá @quinhone uma nova atualização com Pix disponibilizada.
https://github.com/jhernandes/ipag-sdk-php#transa%C3%A7%C3%A3o-com-pix
