### ISSUE TITLE
Erro com Cloudflare

### ISSUE THREAD

**Issue by pedroluizsro** [jhernandes/ipag-sdk-php#14]
Boa tarde,

Gostaria de saber se este SDK continuará tendo suporte?
Estamos utilizando e sexta-feira as submissões de pagamento pararam de funcionar, solicitando resolução do Captcha no link de API do iPag.
Já entrei em contato direto com o iPag e nada do pessoal resolver.

**Comment by jhernandes** [comment]
Bom dia Pedro,
Sim, o SDK continuará tendo suporte.
O bloqueio ocorreu devido a origem das chamadas terem sido bloqueadas pelo Firewall do iPag.
Acredito que a equipe já tenha dado suporte em relação ao seu chamado.
