### ISSUE TITLE
Controles de Webhook

### ISSUE THREAD

**Issue by ceresaconsultoria** [jhernandes/ipag-sdk-php#15]
Conseguem implementar? Podemos ajudar.

**Comment by edson-nascimento** [comment]
+1

**Comment by jhernandes** [comment]
Boa tarde @ceresaconsultoria e @edson-nascimento. Este plugin foi abandonado.

O iPag criou um plugin oficial com acesso a todos os endpoints disponíveis até o momento, deem uma olhada aqui:

https://github.com/ipagdevs/ipag-sdk-php

Documentação oficial: https://developers.ipag.com.br

**Comment by ceresaconsultoria** [comment]
Perfeito obrigasdo
