### ISSUE TITLE
Documentação do Order capture

### ISSUE THREAD

**Issue by edson-nascimento** [jhernandes/ipag-sdk-php#16]
Seria possível documentar o significado de `c, a, p` do capture no `Order.php`

Atualmente não estou sentando esse campo, vi que o valor `p` é o padrão.

```php
public function setCapture($capture)
    {
        switch ($capture) {
            case 'c':
                $this->capture = 'c';
                break;
            case 'a':
                $this->capture = 'a';
                break;
            default:
                $this->capture = 'p';
                break;
        }

        return $this;
    }
```

**Comment by jhernandes** [comment]
Bom dia @edson-nascimento!

Segue a descrição do que significa cada letra:

"c" => Pré-autorização seguida de Captura
"a" => Pré-Autorização
"p" => Irá recuperar a configuração padrão, definida dentro do Painel do iPag.

Quando uma transação é apenas pré-autorizada, o valor cobrado no cartão fica retido por aproximadamente 5 dias, aguardando uma decisão de captura ou cancelamento. Caso não seja definido dentro dos 5 dias, a transação é cancelada automaticamente e o valor é devolvido para o cliente. Se for capturado, então o valor é faturado na conta do cartão de crédito do cliente, e o lojista recebe o valor programado.

Ficando alguma dúvida me avise.
