### ISSUE TITLE
Adicionar `http_build_query` no `$this->httpPostFields` em `CurlOnlyPostHttpClient.php`

### ISSUE THREAD

**Issue by edson-nascimento** [jhernandes/ipag-sdk-php#20]
Eu estendi a classe `IpagResource` para implementar alguns outros endpoints da api, mas estou com um problema, pois a `CurlOnlyPostHttpClient` não está serializando o body da maneira correta quando o `array` tem mais de um nível
 Ex
 ```php
$body = [
    "http_method" =>"POST",
    "url" => "https://minhaloja.com.br/callback",
    "description" => "Webhook para receber notificações de atualização das transações",
    "actions" => [
        "TransactionCreated",
        "TransactionWaitingPayment",
        "TransactionCanceled",
        "TransactionPreAuthorized",
        "TransactionCaptured",
        "TransactionDenied",
        "TransactionDisputed",
        "TransactionChargedback"
    ]
];
$this->sendHttpRequest($this->generateEndpoint('/service/resources/webhooks'), $body);
```
Nesse caso não serializa o `actions`.

https://github.com/jhernandes/ipag-sdk-php/blob/5dce20e0c17349c3418c73a0fb10adecfe28f4b4/src/Ipag/Classes/Http/CurlOnlyPostHttpClient.php#L23-L30

Sugestão usar `http_build_query` na linha 26 para serializar automaticamente todos os níveis.
```php
$this->httpPostFields = http_build_query($fields);
```

Eu não fiz o pull request, pois não sei se essa alteração afeta alguma regra da api de vocês.

**Comment by jhernandes** [comment]
Oi @edson-nascimento este projeto foi abandonado. Sugiro utilizar o SDK oficial do iPag:

https://github.com/ipagdevs/ipag-sdk-php

Att,
