### ISSUE TITLE
Resolver problemas de conexão com ipv6

### ISSUE THREAD

**Issue by weslleyceresa** [jhernandes/ipag-sdk-php#4]
Adicionar na lib a linha:
curl_setopt($ch, CURLOPT_IPRESOLVE, CURL_IPRESOLVE_V4);

para resolver problemas de conexão com ipv6

**Comment by jhernandes** [comment]
Olá @weslleyceresa farei alguns testes, e se não tiver nenhum problema, estará incluído na próxima versão.

Abraço!
