### ISSUE TITLE
Captura parcial

### ISSUE THREAD

**Issue by raulamoretti** [jhernandes/ipag-sdk-php#5]
Pessoal estou desenvolvendo um projeto com a iPag e estou usando a lib de vocês!
Preciso na captura passar o valor parcial, mas não foi implementado na biblioteca o campo é valor.

"valor | 10 | float | não | Valor desejado do cancelamento, pode ser igual ou menor o valor da transação."

**Comment by ipagteam** [comment]
Ola @raulamoretti estamos atualizando, e na próxima versão do SDK já estará disponível a opção de cancelamento e captura parcial.

**Comment by jhernandes** [comment]
https://github.com/jhernandes/ipag-sdk-php/releases/tag/v1.1.0
