### ISSUE TITLE
[sandbox] Resposta vazia

### ISSUE THREAD

**Issue by ssgoncalves** [jhernandes/ipag-sdk-php#6]
Ao executar uma transação de pagamento, a mesma é enviada ao sandbox Ipag, porém o response do resquest é vazio, desta forma lançando uma excpetion com a mensagem "Não foi possível identificar o XML de retorno."

array:33 [▼
  "retorno_tipo" => "xml"
  "boleto_tipo" => "xml"
  "identificacao" => "ocultado%40hotmail.com"
  "pedido" => "4"
  "operacao" => "Pagamento"
  "url_retorno" => "ocultado"
  "valor" => "50"
  "parcelas" => "1"
  "vencto" => ""
  "stelo_fingerprint" => ""
  "ip" => ""
  "antifraude" => ""
  "visitorId" => ""
  "captura" => "p"
  "metodo" => "mastercard"
  "num_cartao" => "ocultado"
  "nome_cartao" => "ocultado"
  "mes_cartao" => "09"
  "ano_cartao" => "2019"
  "cvv_cartao" => "831"
  "descricao_pedido" => "%7B%221%22%3A%7B%22descr%22%3A%22Avan%5Cu00e7ado%22%2C%22valor%22%3A50%2C%22quant%22%3A1%2C%22id%22%3A%227%22%7D%7D"
  "nome" => "Administrador+da+plataforma+0502"
  "email" => "ocultado"
  "doc" => "24816427910"
  "fone" => ""
  "endereco" => "Rua+Alagoas"
  "numero_endereco" => "2886"
  "complemento" => "sala+10"
  "bairro" => "Centro"
  "cidade" => "CAMPO+GRANDE"
  "estado" => "MS"
  "pais" => "BR"
  "cep" => "79020000"
]

**Comment by jhernandes** [comment]
Olá @samuelgs verifiquei que você está sempre enviando o mesmo número de pedido. Tente enviar número diferentes a cada chamada.

**Comment by ssgoncalves** [comment]
@jhernandes o problema ocorre desde o primeiro envio, para ter certeza fiz novos testes.

**Comment by jhernandes** [comment]
@ssgoncalves verifiquei que os métodos de pagamentos estava configurados de forma errada. Já regularizei com métodos de homologação da Cielo.

Pode realizar novamente um teste?

**Comment by ssgoncalves** [comment]
Agora está ok. Obrigado.
