### ISSUE TITLE
Problemas com o retotrno

### ISSUE THREAD

**Issue by eudovic** [jhernandes/ipag-sdk-php#9]
Tenho tido este retorno a cada compra com status 5 ou 8
"{\"error\":\"N\\u00e3o foi poss\\u00edvel identificar o XML de retorno.\"}"

Ao comentar a linha que retorno este erro em XmlService é possivel notar que o erro é gerado por outro motivo

"{\"error\":\"Argument 1 passed to Ipag\\\\Classes\\\\Transaction::populate() must be an instance of stdClass, array given, called in \\/Volumes\\/webserver\\/path_api\\/vendor\\/jhernandes\\/ipag-sdk-php\\/src\\/Ipag\\/Classes\\/Services\\/ApiActionService.php on line 50\"}"

**Comment by jhernandes** [comment]
Bom dia @eudovic você está utilizando a ultima versão do plugin? Já abriu conosco um chamado em nosso suporte?

**Comment by eudovic** [comment]
Estou utilizando o SDK, nao abri chamdo, por onde abro?
Emerson

Em seg., 19 de out. de 2020 às 11:52, João Hernandes <
notifications@github.com> escreveu:

**Comment by jhernandes** [comment]
Emerson, envie um email para suporte@ipag.com.br informando os erros que o time irá auxilia-lo.
